# Generated by Django 3.0.6 on 2020-06-01 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_note', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GenericBeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='g-beer/images/%Y/%m/%d')),
                ('abv', models.FloatField()),
                ('flavor', models.ManyToManyField(to='brewer.Flavor')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewer.Style')),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='beer/images/%Y/%m/%d')),
                ('abv', models.FloatField(blank=True)),
                ('brewer_notes', models.TextField(null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('brewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Brewer')),
                ('flavor', models.ManyToManyField(to='brewer.Flavor')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brewer.Style')),
            ],
        ),
    ]
